In [20]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [21]:
df = pd.read_csv('../dataset/software_defect_prediction_dataset.csv')
df.head()

,lines_of_code,cyclomatic_complexity,num_functions,num_classes,comment_density,code_churn,developer_experience_years,num_developers,commit_frequency,bug_fix_commits,past_defects,test_coverage,duplication_percentage,avg_function_length,depth_of_inheritance,response_for_class,coupling_between_objects,lack_of_cohesion,build_failures,static_analysis_warnings,security_vulnerabilities,performance_issues,defect
0,910,12,7,79,0.59,539,19,4,23,7,23,0.34,0.01,70,1,54,27,0.06,3,20,31,21,1
1,3822,9,197,72,0.30,584,8,8,126,153,19,0.24,0.39,180,5,73,23,0.39,9,154,38,29,1
2,3142,20,99,92,0.11,593,0,6,272,177,2,0.45,0.30,152,5,9,31,0.08,7,425,22,6,1
3,516,39,52,79,0.18,81,12,14,16,0,46,0.82,0.12,159,9,23,12,0.44,2,339,24,12,1
4,4476,27,162,75,0.21,918,14,1,164,109,29,0.46,0.20,169,2,84,9,0.41,3,111,19,2,1

In [22]:
df.describe()

,lines_of_code,cyclomatic_complexity,num_functions,num_classes,comment_density,code_churn,developer_experience_years,num_developers,commit_frequency,bug_fix_commits,past_defects,test_coverage,duplication_percentage,avg_function_length,depth_of_inheritance,response_for_class,coupling_between_objects,lack_of_cohesion,build_failures,static_analysis_warnings,security_vulnerabilities,performance_issues,defect
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.00000,60000.000000,60000.000000
mean,2530.351467,25.085650,99.900683,49.371517,0.300259,500.247800,9.465667,7.492883,150.296117,99.262667,24.521100,0.550005,0.200219,102.109167,4.506767,49.991167,25.099967,0.499512,9.467117,248.720767,24.44745,14.473250,0.970383
std,1428.229382,14.112331,57.367154,28.827881,0.173254,288.724453,5.768672,4.032777,86.375771,57.774507,14.432842,0.258996,0.115574,56.279245,2.866878,28.721025,14.139460,0.289559,5.746556,144.011768,14.46083,8.663821,0.169529
min,50.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.100000,0.000000,5.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1299.000000,13.000000,50.000000,24.000000,0.150000,251.000000,4.000000,4.000000,76.000000,49.000000,12.000000,0.330000,0.100000,53.000000,2.000000,25.000000,13.000000,0.250000,4.000000,124.000000,12.00000,7.000000,1.000000
50%,2534.000000,25.000000,99.000000,49.000000,0.300000,501.000000,9.000000,7.000000,151.000000,99.000000,25.000000,0.550000,0.200000,102.000000,5.000000,50.000000,25.000000,0.500000,9.000000,249.000000,24.00000,14.000000,1.000000
75%,3763.000000,37.000000,149.000000,74.000000,0.450000,750.000000,14.000000,11.000000,225.000000,149.000000,37.000000,0.770000,0.300000,151.000000,7.000000,75.000000,37.000000,0.750000,14.000000,373.000000,37.00000,22.000000,1.000000
max,4999.000000,49.000000,199.000000,99.000000,0.600000,999.000000,19.000000,14.000000,299.000000,199.000000,49.000000,1.000000,0.400000,199.000000,9.000000,99.000000,49.000000,1.000000,19.000000,499.000000,49.00000,29.000000,1.000000

In [23]:
df.columns

Index(['lines_of_code', 'cyclomatic_complexity', 'num_functions',
       'num_classes', 'comment_density', 'code_churn',
       'developer_experience_years', 'num_developers', 'commit_frequency',
       'bug_fix_commits', 'past_defects', 'test_coverage',
       'duplication_percentage', 'avg_function_length', 'depth_of_inheritance',
       'response_for_class', 'coupling_between_objects', 'lack_of_cohesion',
       'build_failures', 'static_analysis_warnings',
       'security_vulnerabilities', 'performance_issues', 'defect'],
      dtype='str')

In [24]:
## Exploratory Data Analysis

In [25]:
import numpy as np

# Basic dataset checks
target = 'defect'
feature_cols = [c for c in df.columns if c != target]

rows, cols = df.shape
print(f"Rows: {rows:,}, Columns: {cols}")
print(f"Feature columns: {len(feature_cols)}")

missing = (df.isna().sum().sort_values(ascending=False))
print("\nMissing values (top 10):")
print(missing.head(10))

print("\nTarget distribution (counts):")
print(df[target].value_counts())
print("\nTarget distribution (proportions):")
print(df[target].value_counts(normalize=True))

# Correlation with target (top 10 by absolute value)
if np.issubdtype(df[target].dtype, np.number):
    corr = (
        df[feature_cols + [target]].corr()[target]
        .drop(target)
        .sort_values(key=np.abs, ascending=False)
    )
    print("\nTop correlations with target:")
    print(corr.head(10))
else:
    print("Target is non-numeric; skipping correlation." )

Rows: 60,000, Columns: 23
Feature columns: 22

Missing values (top 10):
lines_of_code                 0
cyclomatic_complexity         0
num_functions                 0
num_classes                   0
comment_density               0
code_churn                    0
developer_experience_years    0
num_developers                0
commit_frequency              0
bug_fix_commits               0
dtype: int64

Target distribution (counts):
defect
1    58223
0     1777
Name: count, dtype: int64

Target distribution (proportions):
defect
1    0.970383
0    0.029617
Name: proportion, dtype: float64

Top correlations with target:
past_defects                  0.235667
static_analysis_warnings      0.180677
cyclomatic_complexity         0.147572
test_coverage                -0.103759
num_developers                0.006506
developer_experience_years    0.006229
comment_density               0.006078
build_failures                0.005322
performance_issues           -0.004914
code_churn                   -0.004261
Name: defect, dtype: float64

## Modeling Setup: Train/Test Split and Cross-Validation

In [26]:
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

random_state = 42

In [27]:
X = df.drop(columns=[target])
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=random_state
)

print(f"Train shape: {X_train.shape}, Test shape: {X_test.shape}")
print(f"Positive rate (train): {y_train.mean():.3f}, (test): {y_test.mean():.3f}")

Train shape: (48000, 22), Test shape: (12000, 22)
Positive rate (train): 0.970, (test): 0.970

In [28]:
log_reg = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter=200, n_jobs=1, solver="lbfgs", random_state=random_state)),
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=random_state)
cv_scores = cross_val_score(
    log_reg, X, y, cv=cv, scoring="roc_auc", n_jobs=-1
)

print(f"LogReg CV ROC-AUC: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

LogReg CV ROC-AUC: 0.986 ± 0.001

/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

In [29]:
log_reg.fit(X_train, y_train)
y_pred_lr = log_reg.predict(X_test)
y_proba_lr = log_reg.predict_proba(X_test)[:, 1]

def summarize_performance(y_true, y_pred, y_proba):
    metrics = {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred),
        "recall": recall_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred),
        "roc_auc": roc_auc_score(y_true, y_proba),
    }
    for k, v in metrics.items():
        print(f"{k}: {v:.3f}")

print("Logistic Regression (test set):")
summarize_performance(y_test, y_pred_lr, y_proba_lr)

print("\nClassification report:")
print(classification_report(y_test, y_pred_lr))

/home/dilusha/windows/projects/ML research/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Logistic Regression (test set):
accuracy: 0.981
precision: 0.986
recall: 0.994
f1: 0.990
roc_auc: 0.988

Classification report:
              precision    recall  f1-score   support

           0       0.72      0.55      0.62       355
           1       0.99      0.99      0.99     11645

    accuracy                           0.98     12000
   macro avg       0.86      0.77      0.81     12000
weighted avg       0.98      0.98      0.98     12000

In [30]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    n_jobs=1,
    random_state=random_state,
    class_weight="balanced_subsample",
)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

print("Random Forest (test set):")
summarize_performance(y_test, y_pred_rf, y_proba_rf)

Random Forest (test set):
accuracy: 1.000
precision: 1.000
recall: 1.000
f1: 1.000
roc_auc: 1.000

In [31]:
rf_importances = (
    pd.Series(rf.feature_importances_, index=X_train.columns)
    .sort_values(ascending=False)
)

print("Top 10 features by importance (Random Forest):")
display(rf_importances.head(10))

Top 10 features by importance (Random Forest):

past_defects                0.456063
static_analysis_warnings    0.239557
cyclomatic_complexity       0.176459
test_coverage               0.103170
commit_frequency            0.002176
code_churn                  0.002116
bug_fix_commits             0.002051
lines_of_code               0.001940
avg_function_length         0.001594
comment_density             0.001514
dtype: float64

## Overfitting Check and Model Optimization

In [32]:
# Overfitting check: compare train vs test metrics
print("LogReg Train:")
y_pred_lr_train = log_reg.predict(X_train)
y_proba_lr_train = log_reg.predict_proba(X_train)[:, 1]
summarize_performance(y_train, y_pred_lr_train, y_proba_lr_train)

print("\nLogReg Test:")
summarize_performance(y_test, y_pred_lr, y_proba_lr)

print("\nRandom Forest Train:")
y_pred_rf_train = rf.predict(X_train)
y_proba_rf_train = rf.predict_proba(X_train)[:, 1]
summarize_performance(y_train, y_pred_rf_train, y_proba_rf_train)

print("\nRandom Forest Test:")
summarize_performance(y_test, y_pred_rf, y_proba_rf)

LogReg Train:
accuracy: 0.981
precision: 0.986
recall: 0.994
f1: 0.990
roc_auc: 0.986

LogReg Test:
accuracy: 0.981
precision: 0.986
recall: 0.994
f1: 0.990
roc_auc: 0.988

Random Forest Train:
accuracy: 1.000
precision: 1.000
recall: 1.000
f1: 1.000
roc_auc: 1.000

Random Forest Test:
accuracy: 1.000
precision: 1.000
recall: 1.000
f1: 1.000
roc_auc: 1.000

In [33]:
from sklearn.model_selection import RandomizedSearchCV

In [34]:
# Cross-validated ROC-AUC for baseline RF to gauge generalization
cv_scores_rf = cross_val_score(rf, X, y, cv=cv, scoring="roc_auc", n_jobs=-1)
print(f"Random Forest CV ROC-AUC: {cv_scores_rf.mean():.3f} ± {cv_scores_rf.std():.3f}")

Random Forest CV ROC-AUC: 1.000 ± 0.000

In [35]:
# Hyperparameter tuning: Random Forest (light RandomizedSearchCV to avoid heavy compute)
rf_base = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    n_jobs=1,
    random_state=random_state,
    class_weight="balanced_subsample",
)
param_dist = {
    "n_estimators": [120, 200, 280],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"],
}
rf_search = RandomizedSearchCV(
    rf_base,
    param_distributions=param_dist,
    n_iter=12,
    cv=3,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=random_state,
    verbose=1,
)
rf_search.fit(X_train, y_train)

print("Best RF params:")
print(rf_search.best_params_)
print(f"Best CV ROC-AUC: {rf_search.best_score_:.3f}")

rf_best = rf_search.best_estimator_
y_pred_rf_best = rf_best.predict(X_test)
y_proba_rf_best = rf_best.predict_proba(X_test)[:, 1]

print("\nTuned Random Forest (test set):")
summarize_performance(y_test, y_pred_rf_best, y_proba_rf_best)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
Best RF params:
{'n_estimators': 120, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 30}
Best CV ROC-AUC: 1.000

Tuned Random Forest (test set):
accuracy: 1.000
precision: 1.000
recall: 1.000
f1: 1.000
roc_auc: 1.000

In [36]:
# Feature importance from tuned RF
rf_best_importances = (
    pd.Series(rf_best.feature_importances_, index=X_train.columns)
    .sort_values(ascending=False)
)
print("Top 10 features by importance (Tuned RF):")
display(rf_best_importances.head(10))

Top 10 features by importance (Tuned RF):

past_defects                0.449812
static_analysis_warnings    0.251149
cyclomatic_complexity       0.170994
test_coverage               0.104775
code_churn                  0.002196
commit_frequency            0.002015
bug_fix_commits             0.001750
lines_of_code               0.001629
num_functions               0.001484
avg_function_length         0.001445
dtype: float64